[tool.poetry]
name = "nicegui-app"
version = "0.1.0"
description = ""
authors = ["nasudadada"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
nicegui = "^1.4.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
