service: cross-compilation-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true